name: "\U0001F41B Bug Report"
description: Create a report to help us improve if something isn't working as expected.
title: Oops looks like there is an issue
labels: 
 - bug
assignees:
 - tlawrie
body:
 - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is and what you expected to happen.
    validations:
      required: true
 - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        * Commands to run
        * Interactions to cause the issue to happen
 - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information to help us reproduce
      placeholder: |
        * OS: [e.g. MacOS]
        * Browser [e.g. chrome, firefox]
        * Version [e.g. 22]
 - type: textarea
    id: additional
    attributes:
      label: Additional Contenxt
      description: Add any other context about the problem here.
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        If applicable, add screenshots or files to help explain your problem.
